"""empty message

Revision ID: 00eac9e67d37
Revises: 
Create Date: 2024-03-27 12:14:48.110065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00eac9e67d37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome_do_plano', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('servicos_contratados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_cliente', sa.String(length=36), nullable=False),
    sa.Column('id_plano', sa.String(length=36), nullable=False),
    sa.Column('data_contratacao', sa.Date(), nullable=False),
    sa.Column('data_cancelamento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_plano'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicos_contratados')
    op.drop_table('planos')
    # ### end Alembic commands ###
